<?= $this->insert('overall/header')  ?>
<body class="">

  <div id="wrapper">
    <?= $this->insert('overall/nav')  ?>

    <div id="page-wrapper" class="gray-bg">
      <?= $this->insert('overall/top-nav')  ?>

      <!-- Inicio del Contenido del pagina -->
      <div class="wrapper wrapper-content animated fadeInRight">
        <div class="row">
          <div class="col-lg-3 btn btn-ttc">
            <div class="widget style1 ">
              <div class="row">
                <div class="col-xs-4 text-center">
                  <i class="fa fa-trophy fa-5x"></i>
                </div>

                <div class="col-xs-8 text-right">
                  <span>Ganancia Semanal</span>
                  <h2 class="font-bold">$ 4,232</h2>
                </div>
              </div>
            </div>
          </div>
          <a href="producers/comprar">
            <div class="col-lg-3 btn btn-ttc">
              <div class="widget style1 navy-bg ">
                <div class="row">
                  <div class="col-xs-4">
                    <i class="fa fa-users fa-5x"></i>
                  </div>
                  <div class="col-xs-8 text-right">
                    <span>Productores</span>
                    <h2 class="font-bold">26'C</h2>
                  </div>

                </div>
              </div>
            </div>
          </a>
          <a href="deudas">
            <div class="col-lg-3 btn btn-ttc">
              <div class="widget style1 lazur-bg">
                <div class="row">
                  <div class="col-xs-4">
                    <i class="fa fa-arrow-down fa-5x"></i>
                  </div>
                  <div class="col-xs-8 text-right">
                    <span>Deudas</span>
                    <h2 class="font-bold">260</h2>
                  </div>
                </div>
              </div>
            </div>
          </a>

          <a href="ventas">
            <div class="col-lg-3 btn btn-ttc">
              <div class="widget style1 yellow-bg">
                <div class="row">
                  <div class="col-xs-4">
                    <i class="fa fa-line-chart  fa-5x"></i>
                  </div>
                  <div class="col-xs-8 text-right">
                    <span>Ventas</span>

                    <h2 class="font-bold">12</h2>
                  </div>
                </div>
              </div>
            </div>
          </a>
        </div>

        <div class="row">
          <div class="col-lg-6">
            <div class="widget navy-bg no-padding">
              <div class="p-m">
                <h1 class="m-xs">$ 1,540</h1>

                <h3 class="font-bold no-margins">
                  Annual income
                </h3>
                <small>Income form project Alpha.</small>
              </div>
              <div class="flot-chart">
                <div class="flot-chart-content" id="flot-chart1"></div>
              </div>
            </div>
          </div>
          <div class="col-lg-3">
            <div class="widget lazur-bg no-padding">
              <div class="p-m">
                <h1 class="m-xs">$ 210,660</h1>

                <h3 class="font-bold no-margins">
                  Monthly income
                </h3>
                <small>Income form project Beta.</small>
              </div>
              <div class="flot-chart">
                <div class="flot-chart-content" id="flot-chart2"></div>
              </div>
            </div>
          </div>
          <div class="col-lg-3">
            <div class="widget yellw-bg no-padding">
              <div class="p-m">
                <h1 class="m-xs">$ 50,992</h1>

                <h3 class="font-bold no-margins">
                  Half-year revenue margin
                </h3>
                <small>Sales marketing.</small>
              </div>
              <div class="flot-chart">
                <div class="flot-chart-content" id="flot-chart3"></div>
              </div>
            </div>
          </div>


        </div>
      </div>
      <!-- Fin del Contenido del pagina -->


      <?= $this->insert('overall/footer')  ?>

    </body>

    <script>
    $(document).ready(function() {
      setTimeout(function() {
        toastr.options = {
          closeButton: true,
          progressBar: true,
          showMethod: 'slideDown',
          timeOut: 4000
        };
        toastr.success('Bienvenido Administrador', 'Bienvenidos a Natillas Guárico');

      }, 1300);


      var data1 = [
        [0,4],[1,8],[2,5],[3,10],[4,4],[5,16],[6,5],[7,11],[8,6],[9,11],[10,30],[11,10],[12,13],[13,4],[14,3],[15,3],[16,6]
      ];
      var data2 = [
        [0,1],[1,0],[2,2],[3,0],[4,1],[5,3],[6,1],[7,5],[8,2],[9,3],[10,2],[11,1],[12,0],[13,2],[14,8],[15,0],[16,0]
      ];
      $("#flot-dashboard-chart").length && $.plot($("#flot-dashboard-chart"), [
        data1, data2
      ],
      {
        series: {
          lines: {
            show: false,
            fill: true
          },
          splines: {
            show: true,
            tension: 0.4,
            lineWidth: 1,
            fill: 0.4
          },
          points: {
            radius: 0,
            show: true
          },
          shadowSize: 2
        },
        grid: {
          hoverable: true,
          clickable: true,
          tickColor: "#d5d5d5",
          borderWidth: 1,
          color: '#d5d5d5'
        },
        colors: ["#1ab394", "#1C84C6"],
        xaxis:{
        },
        yaxis: {
          ticks: 4
        },
        tooltip: false
      }
    );

    var doughnutData = [
      {
        value: 300,
        color: "#a3e1d4",
        highlight: "#1ab394",
        label: "App"
      },
      {
        value: 50,
        color: "#dedede",
        highlight: "#1ab394",
        label: "Software"
      },
      {
        value: 100,
        color: "#A4CEE8",
        highlight: "#1ab394",
        label: "Laptop"
      }
    ];

    var doughnutOptions = {
      segmentShowStroke: true,
      segmentStrokeColor: "#fff",
      segmentStrokeWidth: 2,
      percentageInnerCutout: 45, // This is 0 for Pie charts
      animationSteps: 100,
      animationEasing: "easeOutBounce",
      animateRotate: true,
      animateScale: false
    };

    var ctx = document.getElementById("doughnutChart").getContext("2d");
    var DoughnutChart = new Chart(ctx).Doughnut(doughnutData, doughnutOptions);

    var polarData = [
      {
        value: 300,
        color: "#a3e1d4",
        highlight: "#1ab394",
        label: "App"
      },
      {
        value: 140,
        color: "#dedede",
        highlight: "#1ab394",
        label: "Software"
      },
      {
        value: 200,
        color: "#A4CEE8",
        highlight: "#1ab394",
        label: "Laptop"
      }
    ];

    var polarOptions = {
      scaleShowLabelBackdrop: true,
      scaleBackdropColor: "rgba(255,255,255,0.75)",
      scaleBeginAtZero: true,
      scaleBackdropPaddingY: 1,
      scaleBackdropPaddingX: 1,
      scaleShowLine: true,
      segmentShowStroke: true,
      segmentStrokeColor: "#fff",
      segmentStrokeWidth: 2,
      animationSteps: 100,
      animationEasing: "easeOutBounce",
      animateRotate: true,
      animateScale: false
    };
    var ctx = document.getElementById("polarChart").getContext("2d");
    var Polarchart = new Chart(ctx).PolarArea(polarData, polarOptions);

  });
  </script>
