<div class="footer">
    <div class="pull-right">
        <strong>NATILLAS GUÁRICO</strong> 2016.
    </div>
    <div>
        <strong>Diseñado por Prinot S.A.</strong> &copy; 2016-2018
    </div>
</div>
<!-- Mainly scripts -->

    <!-- IMPORTANT FOR DEBUG MODE NO DELETE -->
    <?php if (true == DEBUG): ?>
    <script src="views/app/js/jdev.js"></script>
    <?php else: ?>
    <script src="views/backend/js/jquery-2.1.1.js"></script>
    <?php endif ?>

    <!-- Ladda -->
   <script src="views/backend/js/plugins/ladda/spin.min.js"></script>
   <script src="views/backend/js/plugins/ladda/ladda.min.js"></script>
   <script src="views/backend/js/plugins/ladda/ladda.jquery.min.js"></script>

   <script src="views/backend/js/bootstrap.min.js"></script>
   <script src="views/backend/js/plugins/metisMenu/jquery.metisMenu.js"></script>
   <script src="views/backend/js/plugins/slimscroll/jquery.slimscroll.min.js"></script>

   <!-- Flot -->
   <script src="views/backend/js/plugins/flot/jquery.flot.js"></script>
   <script src="views/backend/js/plugins/flot/jquery.flot.tooltip.min.js"></script>
   <script src="views/backend/js/plugins/flot/jquery.flot.spline.js"></script>
   <script src="views/backend/js/plugins/flot/jquery.flot.resize.js"></script>
   <script src="views/backend/js/plugins/flot/jquery.flot.pie.js"></script>

   <!-- Peity -->
   <script src="views/backend/js/plugins/peity/jquery.peity.min.js"></script>
   <script src="views/backend/js/demo/peity-demo.js"></script>

   <!-- Custom and plugin javascript -->
   <script src="views/backend/js/inspinia.js"></script>
   <script src="views/backend/js/plugins/pace/pace.min.js"></script>

   <!-- jQuery UI -->
   <script src="views/backend/js/plugins/jquery-ui/jquery-ui.min.js"></script>

   <!-- GITTER -->
   <script src="views/backend/js/plugins/gritter/jquery.gritter.min.js"></script>

   <!-- Sparkline -->
   <script src="views/backend/js/plugins/sparkline/jquery.sparkline.min.js"></script>

   <!-- Sparkline demo data  -->
   <script src="views/backend/js/demo/sparkline-demo.js"></script>

   <!-- ChartJS-->
   <script src="views/backend/js/plugins/chartJs/Chart.min.js"></script>

   <!-- Toastr -->
   <script src="views/backend/js/plugins/toastr/toastr.min.js"></script>


   <!-- Mainly scripts -->
      <script src="views/backend/js/jquery-2.1.1.js"></script>
      <script src="views/backend/js/bootstrap.min.js"></script>
      <script src="views/backend/js/plugins/metisMenu/jquery.metisMenu.js"></script>
      <script src="views/backend/js/plugins/slimscroll/jquery.slimscroll.min.js"></script>

      <!-- Flot -->
      <script src="views/backend/js/plugins/flot/jquery.flot.js"></script>
      <script src="views/backend/js/plugins/flot/jquery.flot.tooltip.min.js"></script>
      <script src="views/backend/js/plugins/flot/jquery.flot.spline.js"></script>
      <script src="views/backend/js/plugins/flot/jquery.flot.resize.js"></script>
      <script src="views/backend/js/plugins/flot/jquery.flot.pie.js"></script>

      <!-- Peity -->
      <script src="views/backend/js/plugins/peity/jquery.peity.min.js"></script>
      <script src="views/backend/js/demo/peity-demo.js"></script>

      <!-- Custom and plugin javascript -->
      <script src="views/backend/js/inspinia.js"></script>
      <script src="views/backend/js/plugins/pace/pace.min.js"></script>

      <!-- jQuery UI -->
      <script src="views/backend/js/plugins/jquery-ui/jquery-ui.min.js"></script>

      <!-- GITTER -->
      <script src="views/backend/js/plugins/gritter/jquery.gritter.min.js"></script>

      <!-- Sparkline -->
      <script src="views/backend/js/plugins/sparkline/jquery.sparkline.min.js"></script>

      <!-- Sparkline demo data  -->
      <script src="views/backend/js/demo/sparkline-demo.js"></script>

      <!-- ChartJS-->
      <script src="views/backend/js/plugins/chartJs/Chart.min.js"></script>

      <!-- Toastr -->
      <script src="views/backend/js/plugins/toastr/toastr.min.js"></script>

      <!-- Jquery Validate -->
        <script src="views/backend/js/plugins/validate/jquery.validate.min.js"></script>
        <script src="views/backend/js/plugins/dataTables/datatables.min.js"></script>
        <script src="views/backend/js/plugins/jeditable/jquery.jeditable.js"></script>


<!-- Chosen -->
    <script src="views/backend/js/plugins/chosen/chosen.jquery.js"></script>

   <!-- JSKnob -->
   <script src="views/backend/js/plugins/jsKnob/jquery.knob.js"></script>

   <!-- Input Mask-->
    <script src="views/backend/js/plugins/jasny/jasny-bootstrap.min.js"></script>

   <!-- Data picker -->
   <script src="views/backend/js/plugins/datapicker/bootstrap-datepicker.js"></script>

   <!-- NouSlider -->
   <script src="views/backend/js/plugins/nouslider/jquery.nouislider.min.js"></script>

   <!-- Switchery -->
   <script src="views/backend/js/plugins/switchery/switchery.js"></script>

    <!-- IonRangeSlider -->
    <script src="views/backend/js/plugins/ionRangeSlider/ion.rangeSlider.min.js"></script>

    <!-- iCheck -->
    <script src="views/backend/js/plugins/iCheck/icheck.min.js"></script>

    <!-- MENU -->
    <script src="views/backend/js/plugins/metisMenu/jquery.metisMenu.js"></script>


    <!-- Date range use moment.js same as full calendar plugin -->
    <script src="views/backend/js/plugins/fullcalendar/moment.min.js"></script>



    <!-- Select2 -->
    <script src="views/backend/js/plugins/select2/select2.full.min.js"></script>

    <!-- TouchSpin -->
    <script src="views/backend/js/plugins/touchspin/jquery.bootstrap-touchspin.min.js"></script>
    <!-- Sweet alert -->
    <script src="views/backend/js/plugins/sweetalert/sweetalert.min.js"></script>



<!-- IMPORTANT FOR DEBUG MODE NO DELETE -->

<script src="views/app/js/jquery.numeric.js"></script>

<script>
  $('.numeric').numeric();
</script>
