<!DOCTYPE html>
<html lang="es">

<head>
<base href="<?= URL ?>" />
<meta charset="utf-8">
<meta name="viewport" content="width=device-width, initial-scale=1.0">
<meta http-equiv="X-UA-Compatible" content="IE=edge">
<meta name="application-name" content="<?= APP ?>" />


<link type="image/x-icon" href="views/favicon.ico" rel="shortcut icon" />
  <title><?= APP ?> | .:Natillas Guárico:. </title>


<link href="views/backend/css/bootstrap.min.css" rel="stylesheet">
<link href="views/backend/font-awesome/css/font-awesome.css" rel="stylesheet">
<link href="views/backend/css/plugins/dataTables/datatables.min.css" rel="stylesheet">
<link href="views/backend/css/plugins/iCheck/custom.css" rel="stylesheet">
<link href="views/backend/css/plugins/steps/jquery.steps.css" rel="stylesheet">
<!-- Sweet Alert -->
<link href="views/backend/css/plugins/sweetalert/sweetalert.css" rel="stylesheet">

<!-- Toastr style -->
<link href="views/backend/css/plugins/toastr/toastr.min.css" rel="stylesheet">

<!-- Gritter -->
<link href="views/backend/js/plugins/gritter/jquery.gritter.css" rel="stylesheet">

<link href="views/backend/css/animate.css" rel="stylesheet">
<link href="views/backend/css/style.css" rel="stylesheet">
<link href="views/backend/css/plugins/ladda/ladda-themeless.min.css" rel="stylesheet">

<link href="views/backend/css/plugins/chosen/chosen.css" rel="stylesheet">

<link href="views/backend/css/plugins/colorpicker/bootstrap-colorpicker.min.css" rel="stylesheet">

<link href="views/backend/css/plugins/cropper/cropper.min.css" rel="stylesheet">

<link href="views/backend/css/plugins/switchery/switchery.css" rel="stylesheet">

<link href="views/backend/css/plugins/jasny/jasny-bootstrap.min.css" rel="stylesheet">

<link href="views/backend/css/plugins/nouslider/jquery.nouislider.css" rel="stylesheet">

<link href="views/backend/css/plugins/datapicker/datepicker3.css" rel="stylesheet">

<link href="views/backend/css/plugins/ionRangeSlider/ion.rangeSlider.css" rel="stylesheet">
<link href="views/backend/css/plugins/ionRangeSlider/ion.rangeSlider.skinFlat.css" rel="stylesheet">

<link href="views/backend/css/plugins/awesome-bootstrap-checkbox/awesome-bootstrap-checkbox.css" rel="stylesheet">

<link href="views/backend/css/plugins/clockpicker/clockpicker.css" rel="stylesheet">

<link href="views/backend/css/plugins/daterangepicker/daterangepicker-bs3.css" rel="stylesheet">

<link href="views/backend/css/plugins/select2/select2.min.css" rel="stylesheet">

<link href="views/backend/css/plugins/touchspin/jquery.bootstrap-touchspin.min.css" rel="stylesheet">


</head>
