<nav class="navbar-default navbar-static-side" role="navigation">
    <div class="sidebar-collapse">
        <ul class="nav metismenu" id="side-menu">
            <li class="nav-header">
                <div class="dropdown profile-element"> <span>
                    <img alt="image" class="img-circle" src="views/backend/img/logo.png" />
                     </span>
                    <a data-toggle="dropdown" class="dropdown-toggle" href="#">
                    <span class="clear"> <span class="block m-t-xs"> <strong class="font-bold">Natillas Guárico</strong>
                    </span> <span class="text-muted text-lg block">Administrador<b class="caret"></b></span> </span> </a>

                </div>
                <div class="logo-element">
                    NG
                </div>
            </li>
            <li>
                      <a href="home"><i class="fa fa-th-large"></i> <span class="nav-label">Principal</span> <span class="fa arrow"></span></a>
                      <ul class="nav nav-second-level collapse">
                          <li><a href="home">Principal</a></li>
                          <li><a href="home">Principal</a></li>

                          <li><a href="dashboard_5.html">Principal<span class="label label-primary pull-right">NEW</span></a></li>
                      </ul>
                  </li>
            <li>
                <a href="productores"><i class="fa fa-diamond"></i> <span class="nav-label">Productores</span></a>
            </li>
            <li>
                <a href="ventas"><i class="fa fa-diamond"></i> <span class="nav-label">Ventas</span></a>
            </li>
            <li>
                <a href="deudas"><i class="fa fa-bell"></i> <span class="nav-label">Deudas</span><span class="label label-primary pull-right">NEW</span></a></a>

            </li>

            <li>
                <a href="reportes"><i class="fa fa-laptop"></i> <span class="nav-label">Reportes</span></a>
            </li>

        </ul>

    </div>
</nav>
