<?= $this->insert('overall/header')  ?>
<body class="">

  <div id="wrapper">
    <?= $this->insert('overall/nav')  ?>

    <div id="page-wrapper" class="gray-bg">
      <?= $this->insert('overall/top-nav')  ?>

      <!-- Inicio del Contenido del pagina -->
      <div class="col-lg-3">
          <div class="widget style1 white ">
              <div class="row">
                  <div class="col-xs-4">

                  </div>
                  <div class="col-xs-8 text-right">


                  </div>

              </div>
          </div>
      </div>
<a href="producers/comprar">
<div class="col-lg-3 btn btn-ttc">
<div class="widget style1 tabla-bg ">
  <div class="row">
      <div class="col-xs-4">
          <i class="fa fa-truck fa-5x"></i>
      </div>
      <div class="col-xs-8 text-right">
    <span>Comprar Leche</span>
            <h3 class="font-bold">Demo VePrinot</h3>
      </div>

  </div>
</div>
</div>
</a>
<a href="producers/registrar">
<div class="col-lg-3 btn btn-ttc">
<div class="widget style1 registrar-bg ">
    <div class="row">
        <div class="col-xs-4">
            <i class="fa fa-pencil-square-o fa-5x"></i>
        </div>
        <div class="col-xs-8 text-right">
      <span>Registar Productor</span>
            <h3 class="font-bold">Demo VePrinot</h3>
        </div>

    </div>
</div>
</div>
</a>
<a href="home">
<div class="col-lg-3 btn btn-ttc">
  <div class="widget style1 home-bg ">
      <div class="row">
          <div class="col-xs-4">
              <i class="fa fa-dashboard fa-5x"></i>
          </div>
          <div class="col-xs-8 text-right">
        <span>Principal</span>
              <h3 class="font-bold">Demo VePrinot</h3>
          </div>

      </div>
  </div>
</div>
  </a>
      <div class="row">
        <div class="col-lg-pull-12">



          <div class="row">
            <div class="col-lg-12">
              <div class="ibox float-e-margins">
                <div class="ibox-title">
                  <h5>Compra de Leche Semanal</h5>


                </div>
                <div class="ibox-content">

                  <div class="table-responsive">
                    <table id="dataTables-example"class="table table-striped table-bordered table-hover dataTables-example" >

                      <thead>
                        <tr>
                          <th>Nombre</th>
                          <th>Dirección</th>
                          <th>Telefono</th>
                        </tr>
                      </thead>

                      <tbody>
                        <?php foreach($ml as $m): ?>
                          <tr>
                            <th><?=  $m['nombre_productores']  ?></th>
                            <th><?=  $m['direccion_productores']  ?></th>
                            <th><?=  $m['telefono_productores']  ?></th>
                            </tr>
                        <?php  endforeach?>
                      </tbody>

                      <tfoot>
                        <th>Nombre</th>
                        <th>Dirección</th>
                        <th>Telefono</th>
                      </tfoot>


                    </table>
                  </div>

                </div>
              </div>
            </div>
          </div>
        </div>
      </div>
    </div>







  </div>


  <!-- Fin del Contenido del pagina -->


  <?= $this->insert('overall/footer')  ?>

  <script src="views/app/js/productores.js"></script>
  <script>
    $(document).ready(function() {
      $('#dataTables-example').DataTable({


        "order": [[ 1, "asc" ]],
        "language": {

          "lengthMenu": "Mostar _MENU_ registros por pagina",
          "info": "Mostrando pagina _PAGE_ de _PAGES_",
          "infoEmpty": "No Hay registros Disponibles",
          "infoFiltered": "(filtrada de _MAX_ registros)",
          "search": "Buscar:",
          "paginate": {
            "next":       "Siguiente",
            "previous":   "Anterior"
          },
        }
      });

})



  </script>
