<?= $this->insert('overall/header')  ?>
<body class="">

  <div id="wrapper">
    <?= $this->insert('overall/nav')  ?>

    <div id="page-wrapper" class="gray-bg">
      <?= $this->insert('overall/top-nav')  ?>

      <!-- Inicio del Contenido del pagina -->
      <div class="row">
        <div class="col-lg-12">



          <div class="row">
            <div class="col-lg-12">
              <div class="ibox float-e-margins">
                <div class="ibox-title">
                  <h5>Compra de Leche Semanal</h5>
                  <?php

                  echo jddayofweek ( cal_to_jd(CAL_GREGORIAN, date("m"),date("d"), date("Y")) , 1 );
                  ?>
                </div>
                <div class="ibox-content">

                  <div class="table-responsive">
                    <table class="table table-striped table-bordered table-hover dataTables-example" >

                      <thead>
                        <tr>

                          <th>productor</th>
                          <th>direccion</th>
                          <th>telefono</th>
                          <th>leche</th>
                          <th>Jueves</th>
                          <th>campo relacional producers</th>
                        <th>campo relacional milk</th>

                        </tr>
                      </thead>

                      <tbody>


                        <?php foreach($p as $m): ?>

                          <tr>
                            <th><?=  $m['name_producers']  ?></th>
                            <th><?=  $m['address_producers']  ?></th>
                            <th><?=  $m['phone_producers']  ?></th>
                            <th><?=  $m['quantity_producers']  ?></th>
                            <th><?=  $m['creationdate_producers']  ?></th>
                            <th><?=  $m['ced_producers']  ?></th>
                            <th><?=  $m['ced_milk']  ?></th>
                          </tr>
                        <?php  endforeach?>



                      </tbody>

                      <tfoot>
                        <th>productor</th>
                        <th>Lunes</th>
                        <th>Martes</th>
                        <th>Miercoles</th>
                        <th>Jueves</th>
                        <th>Viernes</th>
                        <th>Sabado</th>
                        
                      </tfoot>


                    </table>
                  </div>

                </div>
              </div>
            </div>
          </div>
        </div>
      </div>
    </div>







  </div>


  <!-- Fin del Contenido del pagina -->

  <!-- IMPORTANT FOR DEBUG MODE NO DELETE -->
  <?php if (true == DEBUG): ?>
    <script src="views/app/js/jdev.js"></script>
  <?php else: ?>
    <script src="views/backend/js/jquery-2.1.1.js"></script>
  <?php endif ?>

  <!-- Ladda -->
  <script src="views/backend/js/plugins/ladda/spin.min.js"></script>
  <script src="views/backend/js/plugins/ladda/ladda.min.js"></script>
  <script src="views/backend/js/plugins/ladda/ladda.jquery.min.js"></script>

  <script src="views/backend/js/bootstrap.min.js"></script>
  <script src="views/backend/js/plugins/metisMenu/jquery.metisMenu.js"></script>
  <script src="views/backend/js/plugins/slimscroll/jquery.slimscroll.min.js"></script>

  <!-- Flot -->
  <script src="views/backend/js/plugins/flot/jquery.flot.js"></script>
  <script src="views/backend/js/plugins/flot/jquery.flot.tooltip.min.js"></script>
  <script src="views/backend/js/plugins/flot/jquery.flot.spline.js"></script>
  <script src="views/backend/js/plugins/flot/jquery.flot.resize.js"></script>
  <script src="views/backend/js/plugins/flot/jquery.flot.pie.js"></script>

  <!-- Peity -->
  <script src="views/backend/js/plugins/peity/jquery.peity.min.js"></script>
  <script src="views/backend/js/demo/peity-demo.js"></script>

  <!-- Custom and plugin javascript -->
  <script src="views/backend/js/inspinia.js"></script>
  <script src="views/backend/js/plugins/pace/pace.min.js"></script>

  <!-- jQuery UI -->
  <script src="views/backend/js/plugins/jquery-ui/jquery-ui.min.js"></script>

  <!-- GITTER -->
  <script src="views/backend/js/plugins/gritter/jquery.gritter.min.js"></script>

  <!-- Sparkline -->
  <script src="views/backend/js/plugins/sparkline/jquery.sparkline.min.js"></script>

  <!-- Sparkline demo data  -->
  <script src="views/backend/js/demo/sparkline-demo.js"></script>

  <!-- ChartJS-->
  <script src="views/backend/js/plugins/chartJs/Chart.min.js"></script>

  <!-- Toastr -->
  <script src="views/backend/js/plugins/toastr/toastr.min.js"></script>


  <!-- Mainly scripts -->
  <script src="views/backend/js/jquery-2.1.1.js"></script>
  <script src="views/backend/js/bootstrap.min.js"></script>
  <script src="views/backend/js/plugins/metisMenu/jquery.metisMenu.js"></script>
  <script src="views/backend/js/plugins/slimscroll/jquery.slimscroll.min.js"></script>

  <!-- Flot -->
  <script src="views/backend/js/plugins/flot/jquery.flot.js"></script>
  <script src="views/backend/js/plugins/flot/jquery.flot.tooltip.min.js"></script>
  <script src="views/backend/js/plugins/flot/jquery.flot.spline.js"></script>
  <script src="views/backend/js/plugins/flot/jquery.flot.resize.js"></script>
  <script src="views/backend/js/plugins/flot/jquery.flot.pie.js"></script>

  <!-- Peity -->
  <script src="views/backend/js/plugins/peity/jquery.peity.min.js"></script>
  <script src="views/backend/js/demo/peity-demo.js"></script>

  <!-- Custom and plugin javascript -->
  <script src="views/backend/js/inspinia.js"></script>
  <script src="views/backend/js/plugins/pace/pace.min.js"></script>

  <!-- jQuery UI -->
  <script src="views/backend/js/plugins/jquery-ui/jquery-ui.min.js"></script>

  <!-- GITTER -->
  <script src="views/backend/js/plugins/gritter/jquery.gritter.min.js"></script>

  <!-- Sparkline -->
  <script src="views/backend/js/plugins/sparkline/jquery.sparkline.min.js"></script>

  <!-- Sparkline demo data  -->
  <script src="views/backend/js/demo/sparkline-demo.js"></script>

  <!-- ChartJS-->
  <script src="views/backend/js/plugins/chartJs/Chart.min.js"></script>

  <!-- Toastr -->
  <script src="views/backend/js/plugins/toastr/toastr.min.js"></script>

  <!-- Jquery Validate -->
  <script src="views/backend/js/plugins/validate/jquery.validate.min.js"></script>
  <script src="views/backend/js/plugins/dataTables/datatables.min.js"></script>
  <script src="views/backend/js/plugins/jeditable/jquery.jeditable.js"></script>


  <!-- Chosen -->
  <script src="views/backend/js/plugins/chosen/chosen.jquery.js"></script>

  <!-- JSKnob -->
  <script src="views/backend/js/plugins/jsKnob/jquery.knob.js"></script>

  <!-- Input Mask-->
  <script src="views/backend/js/plugins/jasny/jasny-bootstrap.min.js"></script>

  <!-- Data picker -->
  <script src="views/backend/js/plugins/datapicker/bootstrap-datepicker.js"></script>

  <!-- NouSlider -->
  <script src="views/backend/js/plugins/nouslider/jquery.nouislider.min.js"></script>

  <!-- Switchery -->
  <script src="views/backend/js/plugins/switchery/switchery.js"></script>

  <!-- IonRangeSlider -->
  <script src="views/backend/js/plugins/ionRangeSlider/ion.rangeSlider.min.js"></script>

  <!-- iCheck -->
  <script src="views/backend/js/plugins/iCheck/icheck.min.js"></script>

  <!-- MENU -->
  <script src="views/backend/js/plugins/metisMenu/jquery.metisMenu.js"></script>


  <!-- Date range use moment.js same as full calendar plugin -->
  <script src="views/backend/js/plugins/fullcalendar/moment.min.js"></script>



  <!-- Select2 -->
  <script src="views/backend/js/plugins/select2/select2.full.min.js"></script>

  <!-- TouchSpin -->
  <script src="views/backend/js/plugins/touchspin/jquery.bootstrap-touchspin.min.js"></script>



  <!-- IMPORTANT FOR DEBUG MODE NO DELETE -->

  <script src="views/app/js/jquery.numeric.js"></script>

  <script>
  $('.numeric').numeric();
  </script>


  <script src="views/app/js/deudas.js"></script>

  <script>
  $(document).ready(function(){
    $('.dataTables-example').DataTable({
      dom: '<"html5buttons"B>lTfgitp',
      buttons: [
        {extend: 'pdf', title: 'Ventas De Leche Semanales'},

        {extend: 'print',
        customize: function (win){
          $(win.document.body).addClass('white-bg');
          $(win.document.body).css('font-size', '12px');

          $(win.document.body).find('table')
          .addClass('compact')
          .css('font-size', 'inherit');
        }
      }
    ]

  });



  /* Init DataTables */
  var oTable = $('#editable').DataTable();

  /* Apply the jEditable handlers to the table */
  oTable.$('td').editable( 'views/backend/example_ajax.php', {
    "callback": function( sValue, y ) {
      var aPos = oTable.fnGetPosition( this );
      oTable.fnUpdate( sValue, aPos[0], aPos[1] );
    },
    "submitdata": function ( value, settings ) {
      return {
        "row_id": this.parentNode.getAttribute('id'),
        "column": oTable.fnGetPosition( this )[2]
      };
    },

    "width": "90%",
    "height": "100%"
  } );


});

</script>
