<?= $this->insert('overall/header')  ?>
<body class="">

  <div id="wrapper">
    <?= $this->insert('overall/nav')  ?>

    <div id="page-wrapper" class="gray-bg">
      <?= $this->insert('overall/top-nav')  ?>

      <!-- Inicio del Contenido del pagina -->
      <div class="col-lg-3">
          <div class="widget style1 white ">
              <div class="row">
                  <div class="col-xs-4">

                  </div>
                  <div class="col-xs-8 text-right">


                  </div>

              </div>
          </div>
      </div>
<a href="ventas/natilla">
<div class="col-lg-3 btn btn-ttc">
<div class="widget style1 tabla-bg ">
  <div class="row">
      <div class="col-xs-4">
          <i class="fa fa-tags fa-5x"></i>
      </div>
      <div class="col-xs-8 text-right">
    <span>Venta de Natilla</span>
            <h3 class="font-bold">Demo VePrinot</h3>
      </div>

  </div>
</div>
</div>
</a>
<a href="ventas/arepero">
<div class="col-lg-3 btn btn-ttc">
<div class="widget style1 registrar-bg ">
    <div class="row">
        <div class="col-xs-4">
            <i class="fa fa-tag fa-5x"></i>
        </div>
        <div class="col-xs-8 text-right">
      <span>Venta de Queso Arepero</span>
            <h3 class="font-bold">Demo VePrinot</h3>
        </div>

    </div>
</div>
</div>
</a>
<a href="home">
<div class="col-lg-3 btn btn-ttc">
  <div class="widget style1 home-bg ">
      <div class="row">
          <div class="col-xs-4">
              <i class="fa fa-dashboard fa-5x"></i>
          </div>
          <div class="col-xs-8 text-right">
        <span>Principal</span>
              <h3 class="font-bold">Demo VePrinot</h3>
          </div>

      </div>
  </div>
</div>
  </a>
      <div class="row">
        <div class="col-lg-pull-12">



          <div class="row">
            <div class="col-lg-12">
              <div class="ibox float-e-margins">
                <div class="ibox-title">
                  <h5>Compra de Leche Semanal</h5>


                </div>
                <div class="ibox-content">

                  <div class="table-responsive">
                    <table id="dataTables-example"class="table table-striped table-bordered table-hover dataTables-example" >

                      <thead>
                        <tr>
                          <th>Productor</th>
                          <th>Leche Semanal</th>
                          <th>Telefono</th>
                        </tr>
                      </thead>

                      <tbody>
                        <?php foreach($vs as $m): ?>
                          <tr>
                            <th><?=  $m['nombre_productores']  ?></th>
                            <th><?=

                              $m['cantidad_leche']

                             ?></th>
                            <th> </th>
                            </tr>
                        <?php  endforeach?>
                      </tbody>

                      <tfoot>
                        <th>Nombre</th>
                        <th>Dirección</th>
                        <th>Telefono</th>
                      </tfoot>


                    </table>
                  </div>
<?php  
$desde = $_POST['desde'];
$hasta = $_POST['hasta'];

//COMPROBAMOS QUE LAS FECHAS EXISTAN
if(isset($desde)==false){
  $desde = $hasta;
}

if(isset($hasta)==false){
  $hasta = $desde;
}

//EJECUTAMOS LA CONSULTA DE BUSQUEDA

$registro = mysql_query("SELECT * FROM productos WHERE fecha_reg BETWEEN '$desde' AND '$hasta' ORDER BY id_prod ASC");

//CREAMOS NUESTRA VISTA Y LA DEVOLVEMOS AL AJAX

echo '<table class="table table-striped table-condensed table-hover">
          <tr>
              <th width="300">Nombre</th>
                <th width="200">Tipo</th>
                <th width="150">Precio Unitario</th>
                <th width="150">Precio Distribuidor</th>
                <th width="150">Fecha Registro</th>
                <th width="50">Opciones</th>
            </tr>';
if(mysql_num_rows($registro)>0){
  while($registro2 = mysql_fetch_array($registro)){
    echo '<tr>
        <td>'.$registro2['nomb_prod'].'</td>
        <td>'.$registro2['tipo_prod'].'</td>
        <td>S/. '.$registro2['precio_unit'].'</td>
        <td>S/. '.$registro2['precio_dist'].'</td>
        <td>'.fechaNormal($registro2['fecha_reg']).'</td>
        <td><a href="javascript:editarProducto('.$registro2['id_prod'].');" class="glyphicon glyphicon-edit"></a> <a href="javascript:eliminarProducto('.$registro2['id_prod'].');" class="glyphicon glyphicon-remove-circle"></a></td>
        </tr>';
  }
}else{
  echo '<tr>
        <td colspan="6">No se encontraron resultados</td>
      </tr>';
}
echo '</table>';?>
                </div>
              </div>
            </div>
          </div>
        </div>
      </div>
    </div>







  </div>


  <!-- Fin del Contenido del pagina -->


  <?= $this->insert('overall/footer')  ?>

  <script src="views/app/js/productores.js"></script>
  <script>
    $(document).ready(function() {
      $('#dataTables-example').DataTable({


        "order": [[ 1, "asc" ]],
        "language": {

          "lengthMenu": "Mostar _MENU_ registros por pagina",
          "info": "Mostrando pagina _PAGE_ de _PAGES_",
          "infoEmpty": "No Hay registros Disponibles",
          "infoFiltered": "(filtrada de _MAX_ registros)",
          "search": "Buscar:",
          "paginate": {
            "next":       "Siguiente",
            "previous":   "Anterior"
          },
        }
      });

})



  </script>
